-- MySQL Script generated by MySQL Workbench
-- Mon Dec  5 14:50:59 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema portfolio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema portfolio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portfolio` DEFAULT CHARACTER SET utf8 ;
USE `portfolio` ;

-- -----------------------------------------------------
-- Table `portfolio`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`usuario` (
  `id` INT NOT NULL,
  `usuario` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `nombre` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`persona` (
  `idpersona` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `localidad` VARCHAR(45) NULL,
  `titulo` VARCHAR(45) NULL,
  `foto_portada` VARCHAR(45) NULL,
  `canvas` VARCHAR(45) NULL,
  `densidad` VARCHAR(45) NULL,
  `interactividad` VARCHAR(45) NULL,
  `particula` VARCHAR(45) NULL,
  `velocidad` VARCHAR(45) NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`idpersona`, `usuario_id`),
  INDEX `fk_persona_usuario_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_persona_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `portfolio`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`experiencia_laboral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`experiencia_laboral` (
  `id` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `subtitulo` VARCHAR(45) NULL,
  `texto` VARCHAR(45) NULL,
  `logo` VARCHAR(45) NULL,
  `link` VARCHAR(255) NULL,
  `fecha_inicio` DATE NULL,
  `fecha_final` DATE NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_experiencia_laboral_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_experiencia_laboral_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `portfolio`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`educacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`educacion` (
  `id` INT NOT NULL,
  `fecha_inicio` DATE NULL,
  `fecha_fin` DATE NULL,
  `titulo` VARCHAR(50) NULL,
  `texto` VARCHAR(250) NULL,
  `logo` VARCHAR(45) NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_educacion_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_educacion_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `portfolio`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`proyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`proyectos` (
  `id` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `texto` VARCHAR(45) NULL,
  `logo` VARCHAR(45) NULL,
  `link` VARCHAR(45) NULL,
  `subtitulo` VARCHAR(45) NULL,
  `fecha_inicio` DATE NULL,
  `fecha_fin` DATE NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_proyectos_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_proyectos_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `portfolio`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`proyecto_logo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`proyecto_logo` (
  `id` INT NOT NULL,
  `logo` VARCHAR(255) NULL,
  `proyecto_id` VARCHAR(45) NULL,
  `proyectos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_proyecto_logo_proyectos1_idx` (`proyectos_id` ASC) VISIBLE,
  CONSTRAINT `fk_proyecto_logo_proyectos1`
    FOREIGN KEY (`proyectos_id`)
    REFERENCES `portfolio`.`proyectos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`aceca_de`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`aceca_de` (
  `id` INT NOT NULL,
  `titulo` VARCHAR(255) NULL,
  `texto` VARCHAR(45) NULL,
  `subtitulo` VARCHAR(45) NULL,
  `visible` TINYINT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_aceca_de_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_aceca_de_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `portfolio`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`skills` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `porcentaje` VARCHAR(45) NULL,
  `color` VARCHAR(45) NULL,
  `texto` VARCHAR(45) NULL,
  `logo` VARCHAR(255) NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_skills_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_skills_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `portfolio`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
